# Generated by Django 3.2.4 on 2021-06-27 21:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('misctype', models.CharField(choices=[('Food', 'Food'), ('Toy', 'Toy')], default='Food', max_length=10)),
                ('dinotype', models.CharField(choices=[('Carnivore', 'Carnivore'), ('Herbivore', 'Herbivore'), ('Piscivore', 'Piscivore')], default='Carnivore', max_length=10)),
                ('size', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], default='Medium', max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('misc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='miscs.misc')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
