# Generated by Django 3.2.4 on 2021-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='type',
            field=models.CharField(choices=[('CARN', 'Carnivore'), ('HERB', 'Herbivore'), ('PISC', 'Piscivore')], default='CARN', max_length=10),
        ),
    ]
