# Generated by Django 3.2.4 on 2021-06-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0002_dinosaur_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='size',
            field=models.CharField(choices=[('LRG', 'Large'), ('MED', 'Medium'), ('SML', 'Small')], default='MED', max_length=10),
        ),
    ]
