# Generated by Django 3.2.4 on 2021-06-13 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0003_dinosaur_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='danger_level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
